---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: get hostname
      shell: "hostname"
      register: "HOSTNAME"
    - name: echo
      debug:
        msg: "{{ HOSTNAME }}"
      
